name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests

    strategy:
      matrix:
        arch: [ amd64, arm64v8, arm32v7 ]
        node: [ 12, 13, 14, 15 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - uses: docker/setup-qemu-action@v1
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: node_modules/.bin/archibald -p -a ${{ matrix.arch }} -n ${{ matrix.node }} .

  linter:
    runs-on: ubuntu-latest
    name: linter

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: Install dependencies
        run: npm install
      - name: Verify code with ESLint
        run: npm run eslint
